# Generated by Django 5.1.6 on 2025-03-16 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_alter_customuser_role_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name of the invoice remark', max_length=255)),
                ('backoffice_code', models.CharField(help_text='Code used in the backoffice system', max_length=50)),
                ('amadeus_code', models.CharField(help_text='Code used in Amadeus', max_length=50)),
                ('is_mandatory', models.BooleanField(default=False, help_text='Whether this remark is mandatory for clients')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Invoice Remark',
                'verbose_name_plural': 'Invoice Remarks',
                'ordering': ['name'],
            },
        ),
    ]
