# Generated by Django 5.1.6 on 2025-03-07 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superuser', 'Superuser'), ('admin', 'Admin'), ('agent', 'Agent'), ('marketing', 'Marketing')], default='agent', max_length=20),
        ),
    ]
