# Generated by Django 5.1.6 on 2025-03-16 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_invoiceremark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceremark',
            name='is_mandatory',
        ),
    ]
