# Generated by Django 5.1.6 on 2025-03-17 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_invoiceremark_is_mandatory'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name of the invoice reference', max_length=255)),
                ('backoffice_code', models.CharField(help_text='Code used in the backoffice system', max_length=50)),
                ('amadeus_code', models.CharField(help_text='Code used in Amadeus', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Invoice Reference',
                'verbose_name_plural': 'Invoice References',
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='InvoiceRemark',
        ),
    ]
