# Generated by Django 5.1.6 on 2025-02-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_support', '0002_alter_agentsupportsupplier_agent_websites'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentsupportsupplier',
            name='other_notes',
            field=models.JSONField(blank=True, default=list, help_text='Additional notes about the supplier', null=True),
        ),
        migrations.AlterField(
            model_name='agentsupportsupplier',
            name='agent_websites',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='agentsupportsupplier',
            name='contact_phone',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='agentsupportsupplier',
            name='general_email',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
