# Generated by Django 5.1.6 on 2025-02-26 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent_support', '0004_supplierattachment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplierattachment',
            old_name='discriptions',
            new_name='description',
        ),
    ]
