# Generated by Django 5.1.6 on 2025-03-06 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('sage_name', models.CharField(blank=True, max_length=255, null=True)),
                ('midoco_crm_number', models.CharField(blank=True, max_length=50, null=True)),
                ('street_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state_province', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField(blank=True, null=True)),
                ('linkedin_social_page', models.URLField(blank=True, null=True)),
                ('industry', models.CharField(max_length=255)),
                ('company_type', models.CharField(default='Prospect Client', max_length=255)),
                ('ops_team', models.CharField(blank=True, max_length=255, null=True)),
                ('account_status', models.CharField(default='Lead', max_length=255)),
                ('invoicing_type', models.CharField(blank=True, max_length=100, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('last_activity_date', models.DateTimeField(blank=True, null=True)),
                ('has_new_contract_signed', models.BooleanField(default=False)),
                ('signed_up_corporate_schemes', models.BooleanField(default=False)),
                ('signed_up_travelogix', models.BooleanField(default=False)),
                ('meetings_events_requirements', models.BooleanField(default=False)),
                ('reporting_standard_bespoke', models.BooleanField(default=False)),
                ('access_to_travelogix', models.BooleanField(default=False)),
                ('travel_policy_health_check_offered', models.BooleanField(default=False)),
                ('testimonial_requested', models.BooleanField(default=False)),
                ('communicated_esg_support', models.BooleanField(default=False)),
                ('receive_co2_reporting', models.BooleanField(default=False)),
                ('discussed_offsetting', models.BooleanField(default=False)),
                ('our_goals', models.TextField(blank=True, null=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='accounts.business')),
                ('company_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('linked_companies', models.ManyToManyField(blank=True, related_name='linked_to', to='crm.company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(blank=True, max_length=100)),
                ('fop_limit', models.CharField(blank=True, max_length=100)),
                ('invoice_references', models.TextField(blank=True)),
                ('corporate_hotel_rates', models.TextField(blank=True)),
                ('corporate_airline_fares', models.TextField(blank=True)),
                ('company_memberships', models.TextField(blank=True)),
                ('travel_policy', models.TextField(blank=True)),
                ('flight_notes', models.TextField(blank=True)),
                ('accommodation_notes', models.TextField(blank=True)),
                ('car_hire_notes', models.TextField(blank=True)),
                ('transfer_notes', models.TextField(blank=True)),
                ('rail_notes', models.TextField(blank=True)),
                ('other_notes', models.TextField(blank=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='crm.company')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('job_title', models.CharField(max_length=100)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('is_primary_contact', models.BooleanField(default=False)),
                ('is_travel_booker_contact', models.BooleanField(default=False)),
                ('is_traveller_contact', models.BooleanField(default=False)),
                ('is_vip_traveller_contact', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='crm.company')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=100)),
                ('online_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('offline_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_fees', to='crm.company')),
            ],
        ),
    ]
