# Generated by Django 5.1.6 on 2025-03-15 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_rename_ops_team_company_client_ops_team_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='access_to_travelogix',
        ),
        migrations.RemoveField(
            model_name='company',
            name='client_account_manager',
        ),
        migrations.RemoveField(
            model_name='company',
            name='client_ops_team',
        ),
        migrations.RemoveField(
            model_name='company',
            name='client_status',
        ),
        migrations.RemoveField(
            model_name='company',
            name='client_type',
        ),
        migrations.RemoveField(
            model_name='company',
            name='communicated_esg_support',
        ),
        migrations.RemoveField(
            model_name='company',
            name='company_memberships',
        ),
        migrations.RemoveField(
            model_name='company',
            name='corporate_airline_fares',
        ),
        migrations.RemoveField(
            model_name='company',
            name='corporate_hotel_rates',
        ),
        migrations.RemoveField(
            model_name='company',
            name='discussed_offsetting',
        ),
        migrations.RemoveField(
            model_name='company',
            name='fop_limit',
        ),
        migrations.RemoveField(
            model_name='company',
            name='has_new_contract_signed',
        ),
        migrations.RemoveField(
            model_name='company',
            name='invoice_references',
        ),
        migrations.RemoveField(
            model_name='company',
            name='invoicing_frequency',
        ),
        migrations.RemoveField(
            model_name='company',
            name='invoicing_type',
        ),
        migrations.RemoveField(
            model_name='company',
            name='meetings_events_requirements',
        ),
        migrations.RemoveField(
            model_name='company',
            name='midoco_crm_number',
        ),
        migrations.RemoveField(
            model_name='company',
            name='our_goals',
        ),
        migrations.RemoveField(
            model_name='company',
            name='payment_terms',
        ),
        migrations.RemoveField(
            model_name='company',
            name='receive_co2_reporting',
        ),
        migrations.RemoveField(
            model_name='company',
            name='reporting_standard_bespoke',
        ),
        migrations.RemoveField(
            model_name='company',
            name='sage_name',
        ),
        migrations.RemoveField(
            model_name='company',
            name='signed_up_corporate_schemes',
        ),
        migrations.RemoveField(
            model_name='company',
            name='signed_up_travelogix',
        ),
        migrations.RemoveField(
            model_name='company',
            name='supplier_for_department',
        ),
        migrations.RemoveField(
            model_name='company',
            name='supplier_owner',
        ),
        migrations.RemoveField(
            model_name='company',
            name='supplier_status',
        ),
        migrations.RemoveField(
            model_name='company',
            name='supplier_type',
        ),
        migrations.RemoveField(
            model_name='company',
            name='testimonial_requested',
        ),
        migrations.RemoveField(
            model_name='company',
            name='travel_policy_health_check_offered',
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_type', models.CharField(choices=[('White Glove Client', 'White Glove Client'), ('Online Client', 'Online Client'), ('Blended', 'Blended'), ('Supplier', 'Supplier')], default='White Glove Client', max_length=255)),
                ('client_status', models.CharField(choices=[('Trading', 'Trading'), ('No longer Trading', 'No longer Trading'), ('On hold', 'On hold'), ('Other', 'Other')], default='Trading', max_length=255)),
                ('sage_name', models.CharField(blank=True, max_length=255, null=True)),
                ('midoco_crm_number', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_references', models.TextField(blank=True)),
                ('invoicing_type', models.CharField(blank=True, max_length=100, null=True)),
                ('invoicing_frequency', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_terms', models.CharField(blank=True, max_length=100, null=True)),
                ('client_ops_team', models.CharField(blank=True, max_length=255, null=True)),
                ('corporate_hotel_rates', models.TextField(blank=True)),
                ('corporate_airline_fares', models.TextField(blank=True)),
                ('company_memberships', models.TextField(blank=True)),
                ('has_new_contract_signed', models.BooleanField(default=False)),
                ('signed_up_corporate_schemes', models.BooleanField(default=False)),
                ('signed_up_travelogix', models.BooleanField(default=False)),
                ('meetings_events_requirements', models.BooleanField(default=False)),
                ('reporting_standard_bespoke', models.BooleanField(default=False)),
                ('access_to_travelogix', models.BooleanField(default=False)),
                ('travel_policy_health_check_offered', models.BooleanField(default=False)),
                ('testimonial_requested', models.BooleanField(default=False)),
                ('communicated_esg_support', models.BooleanField(default=False)),
                ('receive_co2_reporting', models.BooleanField(default=False)),
                ('discussed_offsetting', models.BooleanField(default=False)),
                ('client_account_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_clients', to=settings.AUTH_USER_MODEL)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to='crm.company')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_type', models.CharField(choices=[('Air', 'Air'), ('Accommodation', 'Accommodation'), ('Car Hire', 'Car Hire'), ('Transfer', 'Transfer'), ('Rail', 'Rail'), ('Other', 'Other')], default='Air', max_length=255)),
                ('supplier_status', models.CharField(choices=[('Preferred Supplier', 'Preferred Supplier'), ('Non-Preferred Supplier', 'Non-Preferred Supplier'), ('Other', 'Other')], default='Preferred Supplier', max_length=255)),
                ('supplier_for_department', models.CharField(choices=[('Company Supplier', 'Company Supplier'), ('Operations Supplier', 'Operations Supplier'), ('Finance Supplier', 'Finance Supplier'), ('Sales Supplier', 'Sales Supplier'), ('Marketing Supplier', 'Marketing Supplier'), ('Other', 'Other')], default='Company Supplier', max_length=255)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_profile', to='crm.company')),
                ('supplier_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_suppliers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
