# Generated by Django 5.1.6 on 2025-03-15 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_remove_company_access_to_travelogix_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.CharField(choices=[('Agriculture', 'Agriculture'), ('Mining', 'Mining'), ('Oil and Gas Extraction', 'Oil and Gas Extraction'), ('Pharmaceuticals', 'Pharmaceuticals'), ('Biotechnology', 'Biotechnology'), ('Manufacturing', 'Manufacturing'), ('Construction', 'Construction'), ('Wholesale Trade', 'Wholesale Trade'), ('Retail Trade', 'Retail Trade'), ('Transportation', 'Transportation'), ('Warehousing', 'Warehousing'), ('Information', 'Information'), ('Finance', 'Finance'), ('Insurance', 'Insurance'), ('Real Estate', 'Real Estate'), ('Rental and Leasing', 'Rental and Leasing'), ('Professional Services', 'Professional Services'), ('Scientific Services', 'Scientific Services'), ('Technical Services', 'Technical Services'), ('Management of Companies', 'Management of Companies'), ('Administrative Support', 'Administrative Support'), ('Waste Management', 'Waste Management'), ('Educational Services', 'Educational Services'), ('Health Care', 'Health Care'), ('Social Assistance', 'Social Assistance'), ('Arts', 'Arts'), ('Entertainment', 'Entertainment'), ('Recreation', 'Recreation'), ('Accommodation', 'Accommodation'), ('Food Services', 'Food Services'), ('Other Services', 'Other Services'), ('Public Administration', 'Public Administration'), ('Telecommunications', 'Telecommunications'), ('Hospitality', 'Hospitality'), ('Legal Services', 'Legal Services'), ('Media and Broadcasting', 'Media and Broadcasting'), ('Energy', 'Energy'), ('Renewable Energy', 'Renewable Energy'), ('Automotive', 'Automotive'), ('Aerospace', 'Aerospace'), ('Defence', 'Defence'), ('Tourism', 'Tourism')], max_length=255),
        ),
    ]
