# Generated by Django 5.1.6 on 2025-03-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_alter_company_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierprofile',
            name='contract_signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='invoicing_frequency',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='invoicing_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='new_supplier_form_signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='payment_terms',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
