# Generated by Django 5.1.6 on 2025-03-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_supplierprofile_contract_signed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='reporting_standard_bespoke',
            field=models.CharField(choices=[('Standard', 'Standard'), ('Bespoke', 'Bespoke')], default='Standard', max_length=10),
        ),
    ]
