# Generated by Django 5.1.6 on 2025-03-17 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_invoicereference_delete_invoiceremark'),
        ('crm', '0007_alter_clientprofile_reporting_standard_bespoke'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientInvoiceReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_mandatory', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.clientprofile')),
                ('invoice_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.invoicereference')),
            ],
            options={
                'unique_together': {('client_profile', 'invoice_reference')},
            },
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='invoice_reference_options',
            field=models.ManyToManyField(blank=True, related_name='clients', through='crm.ClientInvoiceReference', to='accounts.invoicereference'),
        ),
    ]
