# Generated by Django 5.1.6 on 2025-03-16 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_invoiceremark'),
        ('crm', '0007_alter_clientprofile_reporting_standard_bespoke'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='invoice_remarks',
            field=models.ManyToManyField(blank=True, related_name='clients', to='accounts.invoiceremark'),
        ),
    ]
