# Generated by Django 5.1.6 on 2025-03-18 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_clientinvoicereference_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('parent', 'Parent Company'), ('subsidiary', 'Subsidiary'), ('branch', 'Branch Office'), ('partner', 'Partner'), ('affiliate', 'Affiliate'), ('vendor', 'Vendor'), ('client', 'Client'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('established_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_company_relationships', to=settings.AUTH_USER_MODEL)),
                ('from_company', models.ForeignKey(help_text='Company initiating the relationship', on_delete=django.db.models.deletion.CASCADE, related_name='from_relationships', to='crm.company')),
                ('to_company', models.ForeignKey(help_text='Company receiving the relationship', on_delete=django.db.models.deletion.CASCADE, related_name='to_relationships', to='crm.company')),
            ],
            options={
                'verbose_name': 'Company Relationship',
                'verbose_name_plural': 'Company Relationships',
                'unique_together': {('from_company', 'to_company', 'relationship_type')},
            },
        ),
    ]
