# Generated by Django 5.1.6 on 2025-03-18 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_companyrelationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='hubspot_id',
            field=models.CharField(blank=True, help_text='HubSpot Company ID', max_length=100, null=True),
        ),
    ]
