# Generated by Django 5.1.6 on 2025-03-20 07:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_contact_contactnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienttravelpolicy',
            name='vip_travelers',
            field=models.ManyToManyField(blank=True, related_name='travel_policies', to='crm.contact'),
        ),
        migrations.AlterField(
            model_name='clienttravelpolicy',
            name='effective_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
