# Generated by Django 5.1.6 on 2025-03-21 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_clienttravelpolicy_vip_travelers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='data',
            field=models.JSONField(blank=True, help_text='Stores detailed activity data in JSON format', null=True),
        ),
    ]
