# Generated by Django 5.1.6 on 2025-03-24 17:00

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_activity_delete_emailactivity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Remove the data JSONField and outcome field from Activity model
        migrations.RemoveField(
            model_name='activity',
            name='data',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='outcome',
        ),
        
        # Create EmailActivity model
        migrations.CreateModel(
            name='EmailActivity',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crm.activity')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('email_date', models.DateField()),
                ('email_time', models.TimeField()),
                ('email_outcome', models.CharField(choices=[('Sent', 'Sent'), ('Received', 'Received'), ('Bounced', 'Bounced'), ('Opened', 'Opened'), ('Clicked', 'Clicked')], max_length=50, null=True, blank=True)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='email_attachments/')),
                ('recipients', models.ManyToManyField(blank=True, related_name='email_activities_received', to='crm.contact')),
            ],
            options={
                'verbose_name': 'Email Activity',
                'verbose_name_plural': 'Email Activities',
                'ordering': ['-email_date', '-email_time'],
            },
            bases=('crm.activity',),
        ),
        
        # Create CallActivity model
        migrations.CreateModel(
            name='CallActivity',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crm.activity')),
                ('call_type', models.CharField(choices=[('Inbound', 'Inbound'), ('Outbound', 'Outbound'), ('Missed', 'Missed'), ('Voicemail', 'Voicemail')], max_length=20)),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
                ('summary', models.TextField()),
                ('call_outcome', models.CharField(max_length=255, null=True, blank=True)),
            ],
            options={
                'verbose_name': 'Call Activity',
                'verbose_name_plural': 'Call Activities',
                'ordering': ['-performed_at'],
            },
            bases=('crm.activity',),
        ),
        
        # Create MeetingActivity model
        migrations.CreateModel(
            name='MeetingActivity',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crm.activity')),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
                ('agenda', models.TextField(blank=True)),
                ('minutes', models.TextField(blank=True)),
                ('meeting_outcome', models.CharField(max_length=255, null=True, blank=True)),
                ('attendees', models.ManyToManyField(blank=True, related_name='meetings_attended', to='crm.contact')),
            ],
            options={
                'verbose_name': 'Meeting Activity',
                'verbose_name_plural': 'Meeting Activities',
                'ordering': ['-performed_at'],
            },
            bases=('crm.activity',),
        ),
        
        # Create NoteActivity model
        migrations.CreateModel(
            name='NoteActivity',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crm.activity')),
                ('content', models.TextField()),
                ('is_private', models.BooleanField(default=False)),
                ('note_outcome', models.CharField(max_length=255, null=True, blank=True)),
            ],
            options={
                'verbose_name': 'Note Activity',
                'verbose_name_plural': 'Note Activities',
                'ordering': ['-performed_at'],
            },
            bases=('crm.activity',),
        ),
        
        # Create DocumentActivity model
        migrations.CreateModel(
            name='DocumentActivity',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crm.activity')),
                ('action', models.CharField(choices=[('Uploaded', 'Uploaded'), ('Downloaded', 'Downloaded'), ('Updated', 'Updated'), ('Deleted', 'Deleted')], max_length=50)),
                ('document_outcome', models.TextField(null=True, blank=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.document')),
            ],
            options={
                'verbose_name': 'Document Activity',
                'verbose_name_plural': 'Document Activities',
                'ordering': ['-performed_at'],
            },
            bases=('crm.activity',),
        ),
        
        # Create StatusChangeActivity model
        migrations.CreateModel(
            name='StatusChangeActivity',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crm.activity')),
                ('old_status', models.CharField(max_length=100)),
                ('new_status', models.CharField(max_length=100)),
                ('reason', models.TextField(blank=True)),
                ('status_outcome', models.TextField(null=True, blank=True)),
            ],
            options={
                'verbose_name': 'Status Change Activity',
                'verbose_name_plural': 'Status Change Activities',
                'ordering': ['-performed_at'],
            },
            bases=('crm.activity',),
        ),
        
        # Create PolicyUpdateActivity model
        migrations.CreateModel(
            name='PolicyUpdateActivity',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crm.activity')),
                ('action', models.CharField(choices=[('Created', 'Created'), ('Updated', 'Updated'), ('Deleted', 'Deleted')], max_length=50)),
                ('changes', models.TextField(blank=True)),
                ('policy_outcome', models.TextField(null=True, blank=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.clienttravelpolicy')),
            ],
            options={
                'verbose_name': 'Policy Update Activity',
                'verbose_name_plural': 'Policy Update Activities',
                'ordering': ['-performed_at'],
            },
            bases=('crm.activity',),
        ),
    ] 