# Generated by Django 5.1.6 on 2025-03-25 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_activity_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='outcome',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='callactivity',
            name='call_type',
            field=models.CharField(choices=[('Inbound', 'Inbound'), ('Outbound', 'Outbound'), ('Missed', 'Missed'), ('Voicemail', 'Voicemail')], max_length=50),
        ),
        migrations.AlterField(
            model_name='documentactivity',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.document'),
        ),
        migrations.AlterField(
            model_name='emailactivity',
            name='recipients',
            field=models.ManyToManyField(related_name='received_emails', to='crm.contact'),
        ),
        migrations.AlterField(
            model_name='meetingactivity',
            name='agenda',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='meetingactivity',
            name='attendees',
            field=models.ManyToManyField(related_name='attended_meetings', to='crm.contact'),
        ),
        migrations.AlterField(
            model_name='meetingactivity',
            name='minutes',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='policyupdateactivity',
            name='changes',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='policyupdateactivity',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.clienttravelpolicy'),
        ),
        migrations.AlterField(
            model_name='statuschangeactivity',
            name='reason',
            field=models.TextField(),
        ),
    ]
