# Generated by Django 5.1.6 on 2025-03-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_remove_emailactivity_recipients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailactivity',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
