# Generated by Django 5.1.6 on 2025-03-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0022_emailactivity_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_system_activity',
            field=models.BooleanField(default=False, help_text='Indicates if this is an automatically generated system activity'),
        ),
    ]
