# Generated by Django 5.1.6 on 2025-04-11 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0024_alter_activity_activity_type_taskactivity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='related_activity',
            field=models.ForeignKey(blank=True, help_text='The activity this task is following up on.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_up_tasks', to='crm.activity'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('meeting', 'Meeting'), ('call', 'Phone Call'), ('email', 'Email'), ('note', 'Note'), ('document', 'Document Upload'), ('status_change', 'Status Change'), ('policy_update', 'Policy Update'), ('waiver', 'Waiver/Favor'), ('task', 'Task'), ('update', 'Update')], max_length=20),
        ),
    ]
