# Generated by Django 5.1.6 on 2025-04-11 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0025_activity_related_activity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskactivity',
            options={'ordering': ['-due_datetime'], 'verbose_name': 'Task Activity', 'verbose_name_plural': 'Task Activities'},
        ),
        migrations.RemoveField(
            model_name='taskactivity',
            name='due_date',
        ),
        migrations.AddField(
            model_name='taskactivity',
            name='due_datetime',
            field=models.DateTimeField(blank=True, help_text='Date and time the task is due.', null=True),
        ),
    ]
