# Generated by Django 5.1.6 on 2025-04-11 07:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0027_taskactivity_reminder_sent_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingactivity',
            name='attendees',
        ),
        migrations.AddField(
            model_name='meetingactivity',
            name='contact_attendees',
            field=models.ManyToManyField(blank=True, related_name='attended_meetings', to='crm.contact'),
        ),
        migrations.AddField(
            model_name='meetingactivity',
            name='user_attendees',
            field=models.ManyToManyField(blank=True, related_name='attended_meetings', to=settings.AUTH_USER_MODEL),
        ),
    ]
