# Generated by Django 5.1.6 on 2025-04-11 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0028_remove_meetingactivity_attendees_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The subject name (must be unique).', max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Note Subject',
                'verbose_name_plural': 'Note Subjects',
                'ordering': ['name'],
            },
        ),
    ]
