# Generated by Django 5.1.6 on 2025-04-12 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0029_notesubject'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaiverFavourType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Waiver & Favour Type',
                'verbose_name_plural': 'Waiver & Favour Types',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='waiveractivity',
            options={'verbose_name': 'Waiver & Favour Activity', 'verbose_name_plural': 'Waiver & Favour Activities'},
        ),
        migrations.RemoveField(
            model_name='noteactivity',
            name='note_outcome',
        ),
        migrations.RemoveField(
            model_name='waiveractivity',
            name='waiver_type',
        ),
        migrations.AddField(
            model_name='noteactivity',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='crm.notesubject'),
        ),
        migrations.AddField(
            model_name='waiveractivity',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='waiver_favour_activities', to='crm.contact'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('email', 'Email'), ('call', 'Call'), ('meeting', 'Meeting'), ('note', 'Note'), ('waiver_favour', 'Waiver & Favour'), ('task', 'Task'), ('document', 'Document Upload'), ('status_change', 'Status Change'), ('policy_update', 'Policy Update')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='notesubject',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='waiveractivity',
            name='reason',
            field=models.TextField(blank=True),
        ),
    ]
