# Generated by Django 5.1.6 on 2025-04-12 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0030_waiverfavourtype_alter_waiveractivity_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='waiveractivity',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waiver_favour_activities', to='crm.waiverfavourtype'),
        ),
    ]
