# Generated by Django 5.1.6 on 2025-04-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0031_add_waiveractivity_type_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noteactivity',
            name='is_private',
        ),
        migrations.AddField(
            model_name='noteactivity',
            name='is_important',
            field=models.BooleanField(db_column='is_private', default=False, help_text='Mark this note as important'),
        ),
    ]
