# Generated by Django 5.1.6 on 2025-05-01 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0032_remove_noteactivity_is_private_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='last_edited_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last edit.', null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, help_text='User who last edited the activity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_activities', to=settings.AUTH_USER_MODEL),
        ),
    ]
