# Generated by Django 5.1.6 on 2025-05-01 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0033_activity_last_edited_at_activity_last_edited_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='noteactivity',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='note_activities', to='crm.contact'),
        ),
    ]
