# Generated by Django 5.1.6 on 2025-05-01 06:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0034_noteactivity_contacts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskactivity',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='taskactivity',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='task_activities', to='crm.contact'),
        ),
        migrations.AddField(
            model_name='taskactivity',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='user_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
