# Generated by Django 5.1.6 on 2025-05-02 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0036_taskactivity_assigned_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waiveractivity',
            options={'verbose_name': 'SAF Activity', 'verbose_name_plural': 'SAF Activities'},
        ),
        migrations.AlterModelOptions(
            name='waiverfavourtype',
            options={'ordering': ['name'], 'verbose_name': 'SAF Type', 'verbose_name_plural': 'SAF Types'},
        ),
        migrations.AddField(
            model_name='waiveractivity',
            name='saf_type',
            field=models.CharField(choices=[('Savings', 'Savings'), ('Allowances', 'Allowances'), ('Favours', 'Favours')], default='Savings', max_length=20),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('email', 'Email'), ('call', 'Call'), ('meeting', 'Meeting'), ('note', 'Note'), ('waiver_favour', 'Savings, Allowances, Favours (SAF)'), ('task', 'Task'), ('document', 'Document Upload'), ('status_change', 'Status Change'), ('policy_update', 'Policy Update')], db_index=True, max_length=20),
        ),
    ]
