# Generated by Django 5.1.6 on 2025-05-02 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0038_waiveractivity_is_missed_saving'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_datetime',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the activity actually occurred', null=True),
        ),
    ]
