# Generated by Django 5.1.6 on 2025-05-02 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0039_activity_activity_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callactivity',
            name='call_outcome',
            field=models.CharField(blank=True, choices=[('completed', 'Completed'), ('left_message', 'Left Message'), ('no_answer', 'No Answer'), ('busy', 'Busy'), ('wrong_number', 'Wrong Number'), ('scheduled_callback', 'Scheduled Callback'), ('', '---------')], max_length=255, null=True),
        ),
    ]
